//
//  SovereignStateInfo.swift
//
//
//  Created by Evan Anderson on 6/16/22.
//

import Foundation

public enum SovereignStateInfo : String, CaseIterable, Jsonable {
    case agriculture_food_apple_production = "Apple Production"
    case agriculture_food_apricot_production = "Apricot Production"
    case agriculture_food_artichoke_production = "Artichoke Production"
    case agriculture_food_avocado_production = "Avocado Production"
    case agriculture_food_cherry_production = "Cherry Production"
    case agriculture_food_coconut_production = "Coconut Production"
    case agriculture_food_coffee_production = "Coffee Production"
    case agriculture_food_cucumber_production = "Cucumber Production"
    case agriculture_food_eggplant_production = "Eggplant Production"
    case agriculture_food_garlic_production = "Garlic Production"
    case agriculture_food_grape_production = "Grape Production"
    case agriculture_food_papaya_production = "Papaya Production"
    case agriculture_food_pear_production = "Pear Production"
    case agriculture_food_pineapple_production = "Pineapple Production"
    case agriculture_food_plum_production = "Plum Production"
    case agriculture_food_potato_production = "Potato Production"
    case agriculture_food_soybean_production = "Soybean Production"
    case agriculture_food_tomato_production = "Tomato Production"
    case agriculture_renewable_electricity_production = "Renewable Electricity Production"
    
    case availability_apple_icloud_plus = "Apple: iCloud+"
    case availability_apple_icloud_hide_my_email = "Apple: iCloud: Hide My Email"
    case availability_apple_ios_card = "Apple Card"
    case availability_apple_ios_carplay = "Apple CarPlay"
    case availability_apple_ios_pay = "Apple Pay"
    case availability_apple_one = "Apple One Bundle"
    case availability_apple_ios_app_store_apps = "Apple App Store: Apps"
    case availability_apple_ios_app_store_games = "Apple App Store: Games"
    case availability_apple_ios_arcade = "Apple Arcade"
    case availability_apple_ios_health_blood_glucose_highlights = "Apple: Health: Blood Glucose Highlights"
    case availability_apple_ios_health_download_health_records_to_iphone = "Apple: Health: Download Health Records to iPhone"
    case availability_apple_ios_health_share_health_app_data_with_healthcare_providers = "Apple: Health: Share Health App Data with healthcare Providers"
    case availability_apple_ios_itunes_store_movies = "Apple: iTunes Store: Movies"
    case availability_apple_ios_itunes_store_music = "Apple: iTunes Store: Music"
    case availability_apple_ios_itunes_store_ringtones_and_tones = "Apple: iTunes Store: Ringtones & Tones"
    case availability_apple_ios_itunes_store_tv_shows = "Apple: iTunes Store: TV Shows"
    case availability_apple_ios_maps_congestion_zones = "Apple Maps: Congestion Zones"
    case availability_apple_ios_maps_directions = "Apple Maps: Directions"
    case availability_apple_ios_maps_speed_cameras = "Apple Maps: Speed Cameras"
    case availability_apple_ios_maps_speed_limits = "Apple Maps: Speed Limits"
    case availability_apple_ios_maps_nearby = "Apple Maps: Nearby"
    case availability_apple_ios_music = "Apple Music"
    case availability_apple_ios_siri = "Apple Siri"
    case availability_apple_ios_tv_app = "Apple TV App"
    case availability_apple_ios_tv_plus = "Apple TV+"
    case availability_apple_ios_podcasts = "Apple Podcasts"
    case availability_apple_ios_news = "Apple News"
    case availability_apple_ios_news_audio = "Apple News Audio"
    case availability_apple_ios_news_plus = "Apple News+"
    
    case availability_apple_watch_os_apple_music = "Apple Watch: Apple Music"
    case availability_apple_watch_os_apple_pay = "Apple Watch: Apple Pay"
    case availability_apple_watch_os_blood_oxygen_app = "Apple Watch: Blood Oxygen App"
    case availability_apple_watch_os_ecg = "Apple Watch: ECG"
    case availability_apple_watch_os_irregular_rhythm_notifications = "Apple Watch: Irregular Rhythm Notifications"
    case availability_apple_watch_os_radio = "Apple Watch: Radio"
    case availability_apple_watch_os_siri = "Apple Watch: Siri"
    case availability_apple_watch_os_student_id_cards = "Apple Watch: Student ID Cards"
    case availability_apple_watch_os_walkie_talkie = "Apple Watch: Walkie Talkie"
    
    case availabilities = "Availabilities"
    case availability_alexa = "Alexa"
    case availability_amc_plus = "AMC+"
    case availability_at_and_t_tv = "AT&T TV"
    case availability_dazn = "DAZN"
    case availability_discovery_plus = "Discovery+"
    case availability_disney_plus = "Disney+"
    case availability_espn_plus = "ESPN+"
    case availability_google_assistant = "Google Assistant"
    case availability_google_pay = "Google Pay"
    case availability_google_play_pass = "Google Play Pass"
    case availability_hbo_max = "HBO Max"
    case availability_hulu = "Hulu"
    case availability_nvidia_geforce_now = "NVIDIA GeForce NOW"
    case availability_paramount_plus = "Paramount+"
    case availability_peacock = "Peacock"
    case availability_playstation_now = "PlayStation Now"
    case availability_samsung_pay = "Samsung Pay"
    case availability_showtime = "Showtime"
    case availability_spotify = "Spotify"
    case availability_stadia = "Stadia"
    case availability_starz = "Starz"
    case availability_starzplay = "Starzplay"
    case availability_tidal = "Tidal"
    case availability_venmo = "Venmo"
    case availability_xbox_cloud_gaming = "Xbox Cloud Gaming"
    case availability_xbox_game_pass = "Xbox Game Pass"
    case availability_xbox_live = "Xbox Live"
    case availability_youtube_premium = "YouTube Premium"
    case availability_youtube_tv = "YouTube TV"
    
    case geography_volcanoes = "Volcanoes"
 
    case info_age_structure = "Age Structure"
    case info_blood_type_distribution = "Blood Type Distribution"
    case info_median_age = "Median Age"
    case info_minimum_annual_leave = "Minimum Annual Leave"
    case info_minimum_wage = "Minimum Wage"
    
    case legality_abortion = "Abortion"
    case legality_bitcoin = "Bitcoin"
    case legality_cannabis = "Cannabis"
    case legality_drinking_age = "Drinking Age"
    case legality_drug_ayahuasca = "Drug: Ayahuasca"
    case legality_drug_cocaine = "Drug: Cocaine"
    case legality_drug_ibogaine = "Drug: Ibogaine"
    case legality_drug_meth = "Drug: Meth"
    case legality_drug_psilocybin_mushrooms = "Drug: Psychedelic Mushrooms"
    case legality_drug_psychoactive_cactus = "Drug: Psychedelic Cacti"
    case legality_drug_salvia_divinorum = "Drug: Salvia Divinorum"
    case legality_guns = "Firearms"
    case legality_incest = "Incest"
    case legality_marital_rape = "Marital Rape"
    case legality_pornography = "Adult Film"
    case legality_prostitution = "Prostitution"
    case legality_smoking_age = "Smoking"
    
    case national_animals = "National Animals"
    case national_anthem = "National Anthem"
    case national_birds = "National Birds"
    case national_capital = "National Capital"
    case national_parks = "National Parks"
    case national_trees = "National Trees"
    
    case ranking_adult_hiv_prevalence = "Adult HIV Prevalence"
    case ranking_cannabis_use = "Cannabis Use"
    case ranking_civilian_firearms = "Civilian Firearms"
    case ranking_climate_change_performance_index = "Climate Change Performance"
    case ranking_co2_emissions = "CO2 Emissions"
    case ranking_corruption_perception_index = "Corruption Perception"
    case ranking_democracy_index = "Democracy"
    case ranking_divorce_rate = "Divorce Rate"
    case ranking_economic_freedom_index = "Economic Freedom"
    case ranking_education_index = "Education"
    case ranking_electricity_consumption = "Electricity Consumption"
    case ranking_fragile_state_index = "Fragile State"
    case ranking_freedom_rankings = "Freedom"
    case ranking_global_peace_index = "Global Peace"
    case ranking_global_terrorism_index = "Global Terrorism"
    case ranking_homicide_rate = "Homicide Rate"
    case ranking_human_development_index = "Human Development"
    case ranking_incarceration_rate = "Incarceration Rate"
    case ranking_infant_mortality_rate = "Infant Mortality Rate"
    case ranking_inflation_rate = "Inflation Rate"
    case ranking_legatum_prosperity_index = "Prosperity"
    case ranking_life_expectancy = "Life Expectancy"
    case ranking_maternal_mortality_rate = "Maternal Mortality Rate"
    case ranking_natural_disaster_risk = "Natural Disaster Risk"
    case ranking_obesity_rate = "Obesity Rate"
    case ranking_population = "Population"
    case ranking_press_freedom_index = "Press Freedom"
    case ranking_quality_of_life_index = "Quality of Life"
    case ranking_quality_of_nationality = "Quality of Nationality"
    case ranking_social_progress_index = "Social Progress"
    case ranking_suicide_rate = "Suicide Rate"
    case ranking_unemployment_rate = "Unemployment Rate"
    case ranking_world_giving_index = "Generosity"
    case ranking_world_happiness_report = "World Happiness"
    
    case service_apple_ios_maps_flyover = "Flyover"
    case service_cia_values = "CIA Values"
    case service_country_history = "Country History"
    case service_country_events = "Country Events"
    case service_travel_advisories = "Travel Advisories"
    case service_wikipedia = "Wikipedia"
    case service_wikipedia_featured_pictures = "Wikipedia Featured Pictures"
    
    case value_health_care_system = "Health Care System"
    case value_military_enlistment_age = "Military Enlistment Age"
    case value_minimum_driving_age = "Minimum Driving Age"
    case value_system_of_government = "System of Government"
    case value_traffic_side = "Side of traffic"
    case value_voting_age = "Voting Age"
    
    public static func valueOf(string: String) -> SovereignStateInfo? {
        return SovereignStateInfo.allCases.first(where: { string.compare($0.rawValue) == .orderedSame || string.elementsEqual("\($0)") })
    }
}
